In [19]:
import pandas as pd
import spacy
import nltk

In [22]:
fake_data = pd.read_csv('fake_news_data.csv')
fake_data.head()
fake_news = fake_data[['text', 'fake_or_factual']]
fake_news.head()

                                                text fake_or_factual
0  There are two small problems with your analogy...       Fake News
1  Buried in Trump s bonkers interview with New Y...       Fake News
2  Women make up over 50 percent of this country,...       Fake News
3  WASHINGTON (Reuters) - U.S. Defense Secretary ...    Factual News
4  BELFAST (Reuters) - Northern Ireland s politic...    Factual News

POS TAGGING

In [ ]:
nlp = spacy.load('en_core_web_sm')
fake_news = fake_data[fake_data['fake_or_factual'] == 'Fake News']
factual_news = fake_data[fake_data['fake_or_factual'] == 'Factual News']

fake_spacy_doc = list(nlp.pipe(fake_news['text']))
factual_spacy_doc = list(nlp.pipe(factual_news['text']))

,title,text,date,fake_or_factual
0,HOLLYWEIRD LIB SUSAN SARANDON Compares Muslim ...,There are two small problems with your analogy...,"Dec 30, 2015",Fake News
1,Elijah Cummings Called Trump Out To His Face ...,Buried in Trump s bonkers interview with New Y...,"April 6, 2017",Fake News
2,Hillary Clinton Says Half Her Cabinet Will Be...,"Women make up over 50 percent of this country,...","April 26, 2016",Fake News
5,Maxine Waters Makes Teens Chant ‘Impeach 45′ a...,Shame on Teen Vogue! Maxine Waters was a guest...,"Dec 10, 2017",Fake News
6,Jay Carney Let It Slip That He Knows Who Obam...,Former White House Press Secretary in the Obam...,"February 10, 2016",Fake News

In [59]:
fake_tags = []

for doc in fake_spacy_doc: 
    fake_tags.append([{'token': token.text, 'pos tags': token.pos_, 'ner': token.ent_type_} for token in doc])

fake_tags[1][0]

{'token': 'Buried', 'pos tags': 'VERB', 'ner': ''}